#!/bin/bash

xsetroot -cursor_name left_ptr
sxhkd &

bspc config border_width 1
bspc config window_gap 10
bspc config border_radius 11

bspc config split_ratio 0.62
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config gapless_monocle false

setxkbmap -option grp:alt_shift_toggle us,ru &
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config automatic_scheme spiral
exec --no-startup-id picom -f
polybar
